import { AuthProvider } from "@/context/AuthContext";
import "./globals.css";
import HeaderServer from "@/components/globals/header/Server";

export const metadata = {
  title: "College booking App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={""}>
        <AuthProvider>
          <HeaderServer />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
