import { AuthProvider } from "@/context/AuthContext";
import "./globals.css";
import HeaderServer from "@/components/globals/header/Server";
import { GoogleOAuthProvider } from "@react-oauth/google";
import FooterServer from "@/components/globals/footer/Server";

export const metadata = {
  title: "College booking App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={""}>
        <AuthProvider>
          <GoogleOAuthProvider clientId={process.env.GOOGLE_CLIENT_ID}>
            <HeaderServer />
            {children}
            <FooterServer />
          </GoogleOAuthProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
